parameters:
  cache.dir: db

services:
  _defaults:
    autowire: true

  Tarandro\:
    resource: ../src/*

  Tarandro\Command\CurrencyRate:
    public: true

  Tarandro\Service\Cbr:
    arguments:
      $cacheDir: '%cache.dir%'

  Symfony\Component\Filesystem\Filesystem:
    class: \Symfony\Component\Filesystem\Filesystem
