parameters:
  cache.dir: db

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Tarandro\:
    resource: '../src/*'

  Tarandro\Service\Cbr:
    arguments: ['@Symfony\Component\Filesystem\Filesystem', '%cache.dir%']

  Symfony\Component\Filesystem\Filesystem:
    class: \Symfony\Component\Filesystem\Filesystem
